# Generated by Django 5.2.5 on 2025-08-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
